# python run_ee.py --ee_policy=rebatching --max_batch_size=4  --num_requests=500 --shallow_exit_layer=60 --conf_threshold=0.9 > ../outputs_70b_llama3/req_500_batch_4_conf_09/rebatching.txt
# python run_ee.py --ee_policy=eager --max_batch_size=4  --num_requests=500 --shallow_exit_layer=60 --conf_threshold=0.9 > ../outputs_70b_llama3/req_500_batch_4_conf_09/eager.txt
# python run_ee.py --ee_policy=average --max_batch_size=4  --num_requests=500 --shallow_exit_layer=60 --conf_threshold=0.9 > ../outputs_70b_llama3/req_500_batch_4_conf_09/average.txt
# python run_ee.py --ee_policy=lazy --max_batch_size=4  --num_requests=500 --shallow_exit_layer=60 --conf_threshold=0.9 > ../outputs_70b_llama3/req_500_batch_4_conf_09/lazy.txt
# python run_ee.py --ee_policy=off --max_batch_size=4  --num_requests=500 --shallow_exit_layer=60 --conf_threshold=0.9 > ../outputs_70b_llama3/req_500_batch_4_conf_09/off.txt
# python run_ee.py --ee_policy=eager --max_batch_size=1  --num_requests=500 --shallow_exit_layer=60 --conf_threshold=0.9 > ../outputs_70b_llama3/req_500_batch_4_conf_09/ee_batch1.txt

# nsys profile -w true -t cuda,osrt -s cpu --cudabacktrace=true -x true -o nsight_profiles/rebatching_copy_nsight --python-sampling=true --python-sampling-frequency=2 python scripts/run_ee.py --ee_policy=rebatching --max_batch_size=2  --num_requests=4 --shallow_exit_layer=24 --conf_threshold=0.6 --csv_path="/workspace/xutingl/vattention-ee/outputs_13b/" --kv_method="copy" --dataset_name="xsum" >outputs_13b/req_4_batch_2_conf_06_layer_24_rebatching_copy.txt

# nsys profile -w true -t cuda,osrt -s cpu --cudabacktrace=true -x true -o nsight_profiles/rebatching_nocopy_nsight --python-sampling=true --python-sampling-frequency=2 python scripts/run_ee.py --ee_policy=rebatching --max_batch_size=2  --num_requests=4 --shallow_exit_layer=24 --conf_threshold=0.6 --csv_path="/workspace/xutingl/vattention-ee/outputs_13b/" --kv_method="copy" --dataset_name="xsum" >outputs_13b/req_4_batch_2_conf_06_layer_24_rebatching_nocopy.txt

# nsys profile -w true -t cuda,osrt -s cpu --cudabacktrace=true -x true -o nsight_profiles/average_nocopy_nsight --python-sampling=true --python-sampling-frequency=2 python scripts/run_ee.py --ee_policy=average --max_batch_size=2  --num_requests=4 --shallow_exit_layer=24 --conf_threshold=0.6 --csv_path="/workspace/xutingl/vattention-ee/outputs_13b/" --kv_method="copy" --dataset_name="xsum" >outputs_13b/req_4_batch_2_conf_06_layer_24_average_nocopy.txt

# nsys profile -w true -t cuda,osrt -s cpu --cudabacktrace=true -x true -o nsight_profiles/off_nsight --python-sampling=true --python-sampling-frequency=2 python scripts/run_ee.py --ee_policy=off --max_batch_size=2  --num_requests=4 --shallow_exit_layer=24 --conf_threshold=0.6 --csv_path="/workspace/xutingl/vattention-ee/outputs_13b/" --kv_method="copy" --dataset_name="xsum" >outputs_13b/req_4_batch_2_off.txt

# nsys profile -t cuda -o nsight_profiles/rebatching_copy_nsight --python-sampling=true --python-sampling-frequency=2 python scripts/run_ee.py --ee_policy=rebatching --max_batch_size=2  --num_requests=4 --shallow_exit_layer=30 --conf_threshold=0.8 --csv_path="/workspace/xutingl/vattention-ee/outputs_13b_prof/" --kv_method="copy" --dataset_name="xsum" >outputs_13b_prof/req_4_batch_2_layer_30_conf_08_rebatching.txt

# python run_ee.py --ee_policy=off --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.8 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_08_layer_25_off_copy.txt

# python run_ee.py --ee_policy=eager --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.01 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_001_layer_40_eager_copy.txt
# python run_ee.py --ee_policy=eager --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.02 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_002_layer_40_eager_copy.txt
# python run_ee.py --ee_policy=eager --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.05 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_005_layer_40_eager_copy.txt
# python run_ee.py --ee_policy=eager --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.1 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_01_layer_40_eager_copy.txt
# python run_ee.py --ee_policy=eager --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.25 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_025_layer_40_eager_copy.txt
# python run_ee.py --ee_policy=eager --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.5 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_05_layer_40_eager_copy.txt

# python run_ee.py --ee_policy=lazy --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.01 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_001_layer_40_lazy_copy.txt
# python run_ee.py --ee_policy=lazy --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.02 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_002_layer_40_lazy_copy.txt
# python run_ee.py --ee_policy=lazy --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.05 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_005_layer_40_lazy_copy.txt
# python run_ee.py --ee_policy=lazy --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.1 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_01_layer_40_lazy_copy.txt
# python run_ee.py --ee_policy=lazy --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.25 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_025_layer_40_lazy_copy.txt
# python run_ee.py --ee_policy=lazy --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.5 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_05_layer_40_lazy_copy.txt

# python run_ee.py --ee_policy=median --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.01 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_001_layer_40_median_copy.txt
# python run_ee.py --ee_policy=median --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.02 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_002_layer_40_median_copy.txt
# python run_ee.py --ee_policy=median --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.05 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_005_layer_40_median_copy.txt
# python run_ee.py --ee_policy=median --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.1 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_01_layer_40_median_copy.txt
# python run_ee.py --ee_policy=median --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.25 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_025_layer_40_median_copy.txt
# python run_ee.py --ee_policy=median --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.5 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_05_layer_40_median_copy.txt

# python run_ee.py --ee_policy=off --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.01 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_28_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_28_nee_1/req_500_batch_8_conf_001_layer_40_off_copy.txt
# python run_ee.py --ee_policy=rebatching --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.01 --num_ee_threshold=2  --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_30_nee_2/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_30_nee_2/req_500_batch_8_conf_001_layer_40_rebatching_copy.txt
# python run_ee.py --ee_policy=rebatching --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.02 --num_ee_threshold=2  --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_30_nee_2/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_30_nee_2/req_500_batch_8_conf_002_layer_40_rebatching_copy.txt
# python run_ee.py --ee_policy=rebatching --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.05 --num_ee_threshold=2  --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_30_nee_2/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_30_nee_2/req_500_batch_8_conf_005_layer_40_rebatching_copy.txt
# python run_ee.py --ee_policy=rebatching --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.1 --num_ee_threshold=2  --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_30_nee_2/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_30_nee_2/req_500_batch_8_conf_01_layer_40_rebatching_copy.txt
# python run_ee.py --ee_policy=rebatching --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.25 --num_ee_threshold=2  --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_30_nee_2/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_30_nee_2/req_500_batch_8_conf_025_layer_40_rebatching_copy.txt
# python run_ee.py --ee_policy=rebatching --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.5 --num_ee_threshold=2  --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_30_nee_2/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_30_nee_2/req_500_batch_8_conf_05_layer_40_rebatching_copy.txt
# python run_ee.py --ee_policy=lazy --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.01 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_30_nee_2/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_30_nee_2/req_500_batch_8_conf_001_layer_40_lazy_copy.txt
# python run_ee.py --ee_policy=lazy --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.02 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_30_nee_2/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_30_nee_2/req_500_batch_8_conf_002_layer_40_lazy_copy.txt
# python run_ee.py --ee_policy=lazy --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.05 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_30_nee_2/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_30_nee_2/req_500_batch_8_conf_005_layer_40_lazy_copy.txt
# python run_ee.py --ee_policy=lazy --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.1 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_30_nee_2/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_30_nee_2/req_500_batch_8_conf_01_layer_40_lazy_copy.txt
# python run_ee.py --ee_policy=lazy --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.25 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_30_nee_2/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_30_nee_2/req_500_batch_8_conf_025_layer_40_lazy_copy.txt
# python run_ee.py --ee_policy=lazy --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.5 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_30_nee_2/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_30_nee_2/req_500_batch_8_conf_05_layer_40_lazy_copy.txt
# python run_ee.py --ee_policy=latency-only --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.01 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_30_nee_2/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_30_nee_2/req_500_batch_8_conf_001_layer_40_latency-only_copy.txt
# python run_ee.py --ee_policy=latency-only --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.02 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_30_nee_2/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_30_nee_2/req_500_batch_8_conf_002_layer_40_latency-only_copy.txt
# python run_ee.py --ee_policy=latency-only --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.05 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_30_nee_2/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_30_nee_2/req_500_batch_8_conf_005_layer_40_latency-only_copy.txt
# python run_ee.py --ee_policy=latency-only --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.1 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_30_nee_2/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_30_nee_2/req_500_batch_8_conf_01_layer_40_latency-only_copy.txt
# python run_ee.py --ee_policy=latency-only --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.25 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_30_nee_2/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_30_nee_2/req_500_batch_8_conf_025_layer_40_latency-only_copy.txt
# python run_ee.py --ee_policy=latency-only --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.5 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_30_nee_2/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_30_nee_2/req_500_batch_8_conf_05_layer_40_latency-only_copy.txt
# python run_ee.py --ee_policy=median --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.01 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_30_nee_2/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_30_nee_2/req_500_batch_8_conf_001_layer_40_median_copy.txt
# python run_ee.py --ee_policy=median --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.02 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_30_nee_2/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_30_nee_2/req_500_batch_8_conf_002_layer_40_median_copy.txt
# python run_ee.py --ee_policy=median --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.05 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_30_nee_2/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_30_nee_2/req_500_batch_8_conf_005_layer_40_median_copy.txt
# python run_ee.py --ee_policy=median --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.1 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_30_nee_2/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_30_nee_2/req_500_batch_8_conf_01_layer_40_median_copy.txt
# python run_ee.py --ee_policy=off --max_batch_size=8  --num_requests=100 --shallow_exit_layer=15 --conf_threshold=0.25 --model balcony-llama-2-7b --csv_path="/workspace/vattention-ee/outputs_balcony/" --kv_method="copy" --dataset_name="xsum" >../outputs_balcony/req_500_batch_8_conf_021_layer_15_off_copy.txt
# python run_ee.py --ee_policy=median --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.5 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_30_nee_2/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_30_nee_2/req_500_batch_8_conf_05_layer_40_median_copy.txt
# python run_ee.py --ee_policy=off --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.01 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_30_nee_2/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_30_nee_2/req_500_batch_8_layer_40_off_copy.txt

# nee 2
# python run_ee.py --ee_policy=eager --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.01 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_001_layer_40_eager_copy.txt
# python run_ee.py --ee_policy=eager --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.02 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_002_layer_40_eager_copy.txt
# python run_ee.py --ee_policy=eager --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.05 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_005_layer_40_eager_copy.txt
# python run_ee.py --ee_policy=eager --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.1 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_01_layer_40_eager_copy.txt
# python run_ee.py --ee_policy=eager --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.25 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_025_layer_40_eager_copy.txt
# python run_ee.py --ee_policy=eager --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.5 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_05_layer_40_eager_copy.txt

# python run_ee.py --ee_policy=lazy --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.01 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_001_layer_40_lazy_copy.txt
# python run_ee.py --ee_policy=lazy --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.02 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_002_layer_40_lazy_copy.txt
# python run_ee.py --ee_policy=lazy --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.05 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_005_layer_40_lazy_copy.txt
# python run_ee.py --ee_policy=lazy --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.1 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_01_layer_40_lazy_copy.txt
# python run_ee.py --ee_policy=lazy --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.25 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_025_layer_40_lazy_copy.txt
# python run_ee.py --ee_policy=lazy --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.5 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_05_layer_40_lazy_copy.txt

# python run_ee.py --ee_policy=median --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.01 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_001_layer_40_median_copy.txt
# python run_ee.py --ee_policy=median --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.02 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_002_layer_40_median_copy.txt
# python run_ee.py --ee_policy=median --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.05 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_005_layer_40_median_copy.txt
# python run_ee.py --ee_policy=median --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.1 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_01_layer_40_median_copy.txt
# python run_ee.py --ee_policy=median --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.25 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_025_layer_40_median_copy.txt
# python run_ee.py --ee_policy=median --max_batch_size=8  --num_requests=500 --shallow_exit_layer=40 --conf_threshold=0.5 --model="llama-2-70b" --csv_path="/workspace/vattention-ee/outputs_llama-2-70b_mar_27_nee_1/" --kv_method="copy" --dataset_name="xsum" >../outputs_llama-2-70b_mar_27_nee_1/req_500_batch_8_conf_05_layer_40_median_copy.txt


python run_ee.py --model balcony-llama-2-7b \
  --ee_policy rebatching --max_batch_size 4 --num_requests 100 \
  --shallow_exit_layer 18 --conf_threshold 0.5 \
  --qps 10 --kv_method copy --dataset_name xsum \
  --csv_path /workspace/vattention-ee/outputs_balcony/ > /workspace/vattention-ee/outputs_balcony/test_batch_4.txt